/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerResetPasswordRouteImport } from './routes/customer/reset-password'
import { Route as CustomerLoginRouteImport } from './routes/customer/login'
import { Route as CustomerForgotPasswordRouteImport } from './routes/customer/forgot-password'
import { Route as CustomerLayoutRouteImport } from './routes/customer/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as CustomerLayoutIndexRouteImport } from './routes/customer/_layout/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as CustomerLayoutChatRouteImport } from './routes/customer/_layout/chat'
import { Route as CustomerLayoutProfileIndexRouteImport } from './routes/customer/_layout/profile/index'
import { Route as CustomerLayoutPetsIndexRouteImport } from './routes/customer/_layout/pets/index'
import { Route as CustomerLayoutBookingsIndexRouteImport } from './routes/customer/_layout/bookings/index'
import { Route as AdminLayoutReportsIndexRouteImport } from './routes/admin/_layout/reports/index'
import { Route as AdminLayoutPetsIndexRouteImport } from './routes/admin/_layout/pets/index'
import { Route as AdminLayoutMedicalRecordsIndexRouteImport } from './routes/admin/_layout/medical-records/index'
import { Route as AdminLayoutInvoicesIndexRouteImport } from './routes/admin/_layout/invoices/index'
import { Route as AdminLayoutCustomersIndexRouteImport } from './routes/admin/_layout/customers/index'
import { Route as AdminLayoutBookingsIndexRouteImport } from './routes/admin/_layout/bookings/index'
import { Route as CustomerLayoutPetsIdRouteImport } from './routes/customer/_layout/pets/$id'
import { Route as CustomerLayoutBookingsNewRouteImport } from './routes/customer/_layout/bookings/new'
import { Route as CustomerLayoutBookingsIdRouteImport } from './routes/customer/_layout/bookings/$id'
import { Route as AdminLayoutPetsNewRouteImport } from './routes/admin/_layout/pets/new'
import { Route as AdminLayoutPetsIdRouteImport } from './routes/admin/_layout/pets/$id'
import { Route as AdminLayoutMedicalRecordsNewRouteImport } from './routes/admin/_layout/medical-records/new'
import { Route as AdminLayoutMedicalRecordsIdRouteImport } from './routes/admin/_layout/medical-records/$id'
import { Route as AdminLayoutInvoicesNewRouteImport } from './routes/admin/_layout/invoices/new'
import { Route as AdminLayoutInvoicesIdRouteImport } from './routes/admin/_layout/invoices/$id'
import { Route as AdminLayoutCustomersNewRouteImport } from './routes/admin/_layout/customers/new'
import { Route as AdminLayoutCustomersIdRouteImport } from './routes/admin/_layout/customers/$id'
import { Route as AdminLayoutBookingsNewRouteImport } from './routes/admin/_layout/bookings/new'
import { Route as AdminLayoutBookingsIdRouteImport } from './routes/admin/_layout/bookings/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerResetPasswordRoute = CustomerResetPasswordRouteImport.update({
  id: '/customer/reset-password',
  path: '/customer/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerForgotPasswordRoute = CustomerForgotPasswordRouteImport.update({
  id: '/customer/forgot-password',
  path: '/customer/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLayoutRoute = CustomerLayoutRouteImport.update({
  id: '/customer/_layout',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLayoutIndexRoute = CustomerLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const CustomerLayoutChatRoute = CustomerLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const CustomerLayoutProfileIndexRoute =
  CustomerLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const CustomerLayoutPetsIndexRoute = CustomerLayoutPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const CustomerLayoutBookingsIndexRoute =
  CustomerLayoutBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const AdminLayoutReportsIndexRoute = AdminLayoutReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPetsIndexRoute = AdminLayoutPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMedicalRecordsIndexRoute =
  AdminLayoutMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutInvoicesIndexRoute =
  AdminLayoutInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCustomersIndexRoute =
  AdminLayoutCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutBookingsIndexRoute =
  AdminLayoutBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const CustomerLayoutPetsIdRoute = CustomerLayoutPetsIdRouteImport.update({
  id: '/pets/$id',
  path: '/pets/$id',
  getParentRoute: () => CustomerLayoutRoute,
} as any)
const CustomerLayoutBookingsNewRoute =
  CustomerLayoutBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const CustomerLayoutBookingsIdRoute =
  CustomerLayoutBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => CustomerLayoutRoute,
  } as any)
const AdminLayoutPetsNewRoute = AdminLayoutPetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPetsIdRoute = AdminLayoutPetsIdRouteImport.update({
  id: '/pets/$id',
  path: '/pets/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMedicalRecordsNewRoute =
  AdminLayoutMedicalRecordsNewRouteImport.update({
    id: '/medical-records/new',
    path: '/medical-records/new',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMedicalRecordsIdRoute =
  AdminLayoutMedicalRecordsIdRouteImport.update({
    id: '/medical-records/$id',
    path: '/medical-records/$id',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutInvoicesNewRoute = AdminLayoutInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutInvoicesIdRoute = AdminLayoutInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCustomersNewRoute = AdminLayoutCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCustomersIdRoute = AdminLayoutCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsNewRoute = AdminLayoutBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsIdRoute = AdminLayoutBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/customer': typeof CustomerLayoutRouteWithChildren
  '/customer/forgot-password': typeof CustomerForgotPasswordRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/reset-password': typeof CustomerResetPasswordRoute
  '/customer/chat': typeof CustomerLayoutChatRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/customer/': typeof CustomerLayoutIndexRoute
  '/admin/bookings/$id': typeof AdminLayoutBookingsIdRoute
  '/admin/bookings/new': typeof AdminLayoutBookingsNewRoute
  '/admin/customers/$id': typeof AdminLayoutCustomersIdRoute
  '/admin/customers/new': typeof AdminLayoutCustomersNewRoute
  '/admin/invoices/$id': typeof AdminLayoutInvoicesIdRoute
  '/admin/invoices/new': typeof AdminLayoutInvoicesNewRoute
  '/admin/medical-records/$id': typeof AdminLayoutMedicalRecordsIdRoute
  '/admin/medical-records/new': typeof AdminLayoutMedicalRecordsNewRoute
  '/admin/pets/$id': typeof AdminLayoutPetsIdRoute
  '/admin/pets/new': typeof AdminLayoutPetsNewRoute
  '/customer/bookings/$id': typeof CustomerLayoutBookingsIdRoute
  '/customer/bookings/new': typeof CustomerLayoutBookingsNewRoute
  '/customer/pets/$id': typeof CustomerLayoutPetsIdRoute
  '/admin/bookings/': typeof AdminLayoutBookingsIndexRoute
  '/admin/customers/': typeof AdminLayoutCustomersIndexRoute
  '/admin/invoices/': typeof AdminLayoutInvoicesIndexRoute
  '/admin/medical-records/': typeof AdminLayoutMedicalRecordsIndexRoute
  '/admin/pets/': typeof AdminLayoutPetsIndexRoute
  '/admin/reports/': typeof AdminLayoutReportsIndexRoute
  '/customer/bookings/': typeof CustomerLayoutBookingsIndexRoute
  '/customer/pets/': typeof CustomerLayoutPetsIndexRoute
  '/customer/profile/': typeof CustomerLayoutProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customer/forgot-password': typeof CustomerForgotPasswordRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/reset-password': typeof CustomerResetPasswordRoute
  '/customer/chat': typeof CustomerLayoutChatRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/customer': typeof CustomerLayoutIndexRoute
  '/admin/bookings/$id': typeof AdminLayoutBookingsIdRoute
  '/admin/bookings/new': typeof AdminLayoutBookingsNewRoute
  '/admin/customers/$id': typeof AdminLayoutCustomersIdRoute
  '/admin/customers/new': typeof AdminLayoutCustomersNewRoute
  '/admin/invoices/$id': typeof AdminLayoutInvoicesIdRoute
  '/admin/invoices/new': typeof AdminLayoutInvoicesNewRoute
  '/admin/medical-records/$id': typeof AdminLayoutMedicalRecordsIdRoute
  '/admin/medical-records/new': typeof AdminLayoutMedicalRecordsNewRoute
  '/admin/pets/$id': typeof AdminLayoutPetsIdRoute
  '/admin/pets/new': typeof AdminLayoutPetsNewRoute
  '/customer/bookings/$id': typeof CustomerLayoutBookingsIdRoute
  '/customer/bookings/new': typeof CustomerLayoutBookingsNewRoute
  '/customer/pets/$id': typeof CustomerLayoutPetsIdRoute
  '/admin/bookings': typeof AdminLayoutBookingsIndexRoute
  '/admin/customers': typeof AdminLayoutCustomersIndexRoute
  '/admin/invoices': typeof AdminLayoutInvoicesIndexRoute
  '/admin/medical-records': typeof AdminLayoutMedicalRecordsIndexRoute
  '/admin/pets': typeof AdminLayoutPetsIndexRoute
  '/admin/reports': typeof AdminLayoutReportsIndexRoute
  '/customer/bookings': typeof CustomerLayoutBookingsIndexRoute
  '/customer/pets': typeof CustomerLayoutPetsIndexRoute
  '/customer/profile': typeof CustomerLayoutProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/customer/_layout': typeof CustomerLayoutRouteWithChildren
  '/customer/forgot-password': typeof CustomerForgotPasswordRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/reset-password': typeof CustomerResetPasswordRoute
  '/customer/_layout/chat': typeof CustomerLayoutChatRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/customer/_layout/': typeof CustomerLayoutIndexRoute
  '/admin/_layout/bookings/$id': typeof AdminLayoutBookingsIdRoute
  '/admin/_layout/bookings/new': typeof AdminLayoutBookingsNewRoute
  '/admin/_layout/customers/$id': typeof AdminLayoutCustomersIdRoute
  '/admin/_layout/customers/new': typeof AdminLayoutCustomersNewRoute
  '/admin/_layout/invoices/$id': typeof AdminLayoutInvoicesIdRoute
  '/admin/_layout/invoices/new': typeof AdminLayoutInvoicesNewRoute
  '/admin/_layout/medical-records/$id': typeof AdminLayoutMedicalRecordsIdRoute
  '/admin/_layout/medical-records/new': typeof AdminLayoutMedicalRecordsNewRoute
  '/admin/_layout/pets/$id': typeof AdminLayoutPetsIdRoute
  '/admin/_layout/pets/new': typeof AdminLayoutPetsNewRoute
  '/customer/_layout/bookings/$id': typeof CustomerLayoutBookingsIdRoute
  '/customer/_layout/bookings/new': typeof CustomerLayoutBookingsNewRoute
  '/customer/_layout/pets/$id': typeof CustomerLayoutPetsIdRoute
  '/admin/_layout/bookings/': typeof AdminLayoutBookingsIndexRoute
  '/admin/_layout/customers/': typeof AdminLayoutCustomersIndexRoute
  '/admin/_layout/invoices/': typeof AdminLayoutInvoicesIndexRoute
  '/admin/_layout/medical-records/': typeof AdminLayoutMedicalRecordsIndexRoute
  '/admin/_layout/pets/': typeof AdminLayoutPetsIndexRoute
  '/admin/_layout/reports/': typeof AdminLayoutReportsIndexRoute
  '/customer/_layout/bookings/': typeof CustomerLayoutBookingsIndexRoute
  '/customer/_layout/pets/': typeof CustomerLayoutPetsIndexRoute
  '/customer/_layout/profile/': typeof CustomerLayoutProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/customer'
    | '/customer/forgot-password'
    | '/customer/login'
    | '/customer/reset-password'
    | '/customer/chat'
    | '/admin/'
    | '/customer/'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/admin/medical-records/$id'
    | '/admin/medical-records/new'
    | '/admin/pets/$id'
    | '/admin/pets/new'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/pets/$id'
    | '/admin/bookings/'
    | '/admin/customers/'
    | '/admin/invoices/'
    | '/admin/medical-records/'
    | '/admin/pets/'
    | '/admin/reports/'
    | '/customer/bookings/'
    | '/customer/pets/'
    | '/customer/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customer/forgot-password'
    | '/customer/login'
    | '/customer/reset-password'
    | '/customer/chat'
    | '/admin'
    | '/customer'
    | '/admin/bookings/$id'
    | '/admin/bookings/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/admin/medical-records/$id'
    | '/admin/medical-records/new'
    | '/admin/pets/$id'
    | '/admin/pets/new'
    | '/customer/bookings/$id'
    | '/customer/bookings/new'
    | '/customer/pets/$id'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/invoices'
    | '/admin/medical-records'
    | '/admin/pets'
    | '/admin/reports'
    | '/customer/bookings'
    | '/customer/pets'
    | '/customer/profile'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/_layout'
    | '/customer/_layout'
    | '/customer/forgot-password'
    | '/customer/login'
    | '/customer/reset-password'
    | '/customer/_layout/chat'
    | '/admin/_layout/'
    | '/customer/_layout/'
    | '/admin/_layout/bookings/$id'
    | '/admin/_layout/bookings/new'
    | '/admin/_layout/customers/$id'
    | '/admin/_layout/customers/new'
    | '/admin/_layout/invoices/$id'
    | '/admin/_layout/invoices/new'
    | '/admin/_layout/medical-records/$id'
    | '/admin/_layout/medical-records/new'
    | '/admin/_layout/pets/$id'
    | '/admin/_layout/pets/new'
    | '/customer/_layout/bookings/$id'
    | '/customer/_layout/bookings/new'
    | '/customer/_layout/pets/$id'
    | '/admin/_layout/bookings/'
    | '/admin/_layout/customers/'
    | '/admin/_layout/invoices/'
    | '/admin/_layout/medical-records/'
    | '/admin/_layout/pets/'
    | '/admin/_layout/reports/'
    | '/customer/_layout/bookings/'
    | '/customer/_layout/pets/'
    | '/customer/_layout/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  CustomerLayoutRoute: typeof CustomerLayoutRouteWithChildren
  CustomerForgotPasswordRoute: typeof CustomerForgotPasswordRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerResetPasswordRoute: typeof CustomerResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/reset-password': {
      id: '/customer/reset-password'
      path: '/customer/reset-password'
      fullPath: '/customer/reset-password'
      preLoaderRoute: typeof CustomerResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/forgot-password': {
      id: '/customer/forgot-password'
      path: '/customer/forgot-password'
      fullPath: '/customer/forgot-password'
      preLoaderRoute: typeof CustomerForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/_layout': {
      id: '/customer/_layout'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/_layout/': {
      id: '/customer/_layout/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerLayoutIndexRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/customer/_layout/chat': {
      id: '/customer/_layout/chat'
      path: '/chat'
      fullPath: '/customer/chat'
      preLoaderRoute: typeof CustomerLayoutChatRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/profile/': {
      id: '/customer/_layout/profile/'
      path: '/profile'
      fullPath: '/customer/profile/'
      preLoaderRoute: typeof CustomerLayoutProfileIndexRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/pets/': {
      id: '/customer/_layout/pets/'
      path: '/pets'
      fullPath: '/customer/pets/'
      preLoaderRoute: typeof CustomerLayoutPetsIndexRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/bookings/': {
      id: '/customer/_layout/bookings/'
      path: '/bookings'
      fullPath: '/customer/bookings/'
      preLoaderRoute: typeof CustomerLayoutBookingsIndexRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/admin/_layout/reports/': {
      id: '/admin/_layout/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminLayoutReportsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pets/': {
      id: '/admin/_layout/pets/'
      path: '/pets'
      fullPath: '/admin/pets/'
      preLoaderRoute: typeof AdminLayoutPetsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/medical-records/': {
      id: '/admin/_layout/medical-records/'
      path: '/medical-records'
      fullPath: '/admin/medical-records/'
      preLoaderRoute: typeof AdminLayoutMedicalRecordsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/invoices/': {
      id: '/admin/_layout/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminLayoutInvoicesIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/customers/': {
      id: '/admin/_layout/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminLayoutCustomersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings/': {
      id: '/admin/_layout/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminLayoutBookingsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/customer/_layout/pets/$id': {
      id: '/customer/_layout/pets/$id'
      path: '/pets/$id'
      fullPath: '/customer/pets/$id'
      preLoaderRoute: typeof CustomerLayoutPetsIdRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/bookings/new': {
      id: '/customer/_layout/bookings/new'
      path: '/bookings/new'
      fullPath: '/customer/bookings/new'
      preLoaderRoute: typeof CustomerLayoutBookingsNewRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/customer/_layout/bookings/$id': {
      id: '/customer/_layout/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/customer/bookings/$id'
      preLoaderRoute: typeof CustomerLayoutBookingsIdRouteImport
      parentRoute: typeof CustomerLayoutRoute
    }
    '/admin/_layout/pets/new': {
      id: '/admin/_layout/pets/new'
      path: '/pets/new'
      fullPath: '/admin/pets/new'
      preLoaderRoute: typeof AdminLayoutPetsNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/pets/$id': {
      id: '/admin/_layout/pets/$id'
      path: '/pets/$id'
      fullPath: '/admin/pets/$id'
      preLoaderRoute: typeof AdminLayoutPetsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/medical-records/new': {
      id: '/admin/_layout/medical-records/new'
      path: '/medical-records/new'
      fullPath: '/admin/medical-records/new'
      preLoaderRoute: typeof AdminLayoutMedicalRecordsNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/medical-records/$id': {
      id: '/admin/_layout/medical-records/$id'
      path: '/medical-records/$id'
      fullPath: '/admin/medical-records/$id'
      preLoaderRoute: typeof AdminLayoutMedicalRecordsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/invoices/new': {
      id: '/admin/_layout/invoices/new'
      path: '/invoices/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminLayoutInvoicesNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/invoices/$id': {
      id: '/admin/_layout/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminLayoutInvoicesIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/customers/new': {
      id: '/admin/_layout/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminLayoutCustomersNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/customers/$id': {
      id: '/admin/_layout/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminLayoutCustomersIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings/new': {
      id: '/admin/_layout/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminLayoutBookingsNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings/$id': {
      id: '/admin/_layout/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminLayoutBookingsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutBookingsIdRoute: typeof AdminLayoutBookingsIdRoute
  AdminLayoutBookingsNewRoute: typeof AdminLayoutBookingsNewRoute
  AdminLayoutCustomersIdRoute: typeof AdminLayoutCustomersIdRoute
  AdminLayoutCustomersNewRoute: typeof AdminLayoutCustomersNewRoute
  AdminLayoutInvoicesIdRoute: typeof AdminLayoutInvoicesIdRoute
  AdminLayoutInvoicesNewRoute: typeof AdminLayoutInvoicesNewRoute
  AdminLayoutMedicalRecordsIdRoute: typeof AdminLayoutMedicalRecordsIdRoute
  AdminLayoutMedicalRecordsNewRoute: typeof AdminLayoutMedicalRecordsNewRoute
  AdminLayoutPetsIdRoute: typeof AdminLayoutPetsIdRoute
  AdminLayoutPetsNewRoute: typeof AdminLayoutPetsNewRoute
  AdminLayoutBookingsIndexRoute: typeof AdminLayoutBookingsIndexRoute
  AdminLayoutCustomersIndexRoute: typeof AdminLayoutCustomersIndexRoute
  AdminLayoutInvoicesIndexRoute: typeof AdminLayoutInvoicesIndexRoute
  AdminLayoutMedicalRecordsIndexRoute: typeof AdminLayoutMedicalRecordsIndexRoute
  AdminLayoutPetsIndexRoute: typeof AdminLayoutPetsIndexRoute
  AdminLayoutReportsIndexRoute: typeof AdminLayoutReportsIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutBookingsIdRoute: AdminLayoutBookingsIdRoute,
  AdminLayoutBookingsNewRoute: AdminLayoutBookingsNewRoute,
  AdminLayoutCustomersIdRoute: AdminLayoutCustomersIdRoute,
  AdminLayoutCustomersNewRoute: AdminLayoutCustomersNewRoute,
  AdminLayoutInvoicesIdRoute: AdminLayoutInvoicesIdRoute,
  AdminLayoutInvoicesNewRoute: AdminLayoutInvoicesNewRoute,
  AdminLayoutMedicalRecordsIdRoute: AdminLayoutMedicalRecordsIdRoute,
  AdminLayoutMedicalRecordsNewRoute: AdminLayoutMedicalRecordsNewRoute,
  AdminLayoutPetsIdRoute: AdminLayoutPetsIdRoute,
  AdminLayoutPetsNewRoute: AdminLayoutPetsNewRoute,
  AdminLayoutBookingsIndexRoute: AdminLayoutBookingsIndexRoute,
  AdminLayoutCustomersIndexRoute: AdminLayoutCustomersIndexRoute,
  AdminLayoutInvoicesIndexRoute: AdminLayoutInvoicesIndexRoute,
  AdminLayoutMedicalRecordsIndexRoute: AdminLayoutMedicalRecordsIndexRoute,
  AdminLayoutPetsIndexRoute: AdminLayoutPetsIndexRoute,
  AdminLayoutReportsIndexRoute: AdminLayoutReportsIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface CustomerLayoutRouteChildren {
  CustomerLayoutChatRoute: typeof CustomerLayoutChatRoute
  CustomerLayoutIndexRoute: typeof CustomerLayoutIndexRoute
  CustomerLayoutBookingsIdRoute: typeof CustomerLayoutBookingsIdRoute
  CustomerLayoutBookingsNewRoute: typeof CustomerLayoutBookingsNewRoute
  CustomerLayoutPetsIdRoute: typeof CustomerLayoutPetsIdRoute
  CustomerLayoutBookingsIndexRoute: typeof CustomerLayoutBookingsIndexRoute
  CustomerLayoutPetsIndexRoute: typeof CustomerLayoutPetsIndexRoute
  CustomerLayoutProfileIndexRoute: typeof CustomerLayoutProfileIndexRoute
}

const CustomerLayoutRouteChildren: CustomerLayoutRouteChildren = {
  CustomerLayoutChatRoute: CustomerLayoutChatRoute,
  CustomerLayoutIndexRoute: CustomerLayoutIndexRoute,
  CustomerLayoutBookingsIdRoute: CustomerLayoutBookingsIdRoute,
  CustomerLayoutBookingsNewRoute: CustomerLayoutBookingsNewRoute,
  CustomerLayoutPetsIdRoute: CustomerLayoutPetsIdRoute,
  CustomerLayoutBookingsIndexRoute: CustomerLayoutBookingsIndexRoute,
  CustomerLayoutPetsIndexRoute: CustomerLayoutPetsIndexRoute,
  CustomerLayoutProfileIndexRoute: CustomerLayoutProfileIndexRoute,
}

const CustomerLayoutRouteWithChildren = CustomerLayoutRoute._addFileChildren(
  CustomerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  CustomerLayoutRoute: CustomerLayoutRouteWithChildren,
  CustomerForgotPasswordRoute: CustomerForgotPasswordRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerResetPasswordRoute: CustomerResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
